### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by Klerith** [FriOne/ng-io#4] opened 2018-10-17 18:05 UTC
Just install this package because the ng-socket-io is not working.. this actually pass the first issue with ng-socket-io, but now I'm stuck with this :(

Uncaught ReferenceError: global is not defined
    at Object../node_modules/socket.io-parser/is-buffer.js (is-buffer.js:4)
    at __webpack_require__ (bootstrap:83)
    at Object../node_modules/socket.io-parser/binary.js (binary.js:8)
    at __webpack_require__ (bootstrap:83)
    at Object../node_modules/socket.io-parser/index.js (index.js:8)
    at __webpack_require__ (bootstrap:83)
    at Object../node_modules/socket.io-client/lib/index.js (index.js:7)
    at __webpack_require__ (bootstrap:83)
    at Module../node_modules/ng-io/fesm5/ng-io.js (ng-io.js:1)
    at __webpack_require__ (bootstrap:83)

**Comment by Klerith** [comment] 2018-10-17 18:07
According to angular/angular-cli#8160 (comment):

adding the following polyfills.ts should work in Angular@6:

// Add global to window, assigning the value of window itself.
(window as any).global = window;
In any case, this issue should not be resolved IMO, socket.io-client should either remove the implicit dependency on global, or document that a polyfill is needed (by anyone using the pre-bundled sources, not just Angular users)

So add this on my index.html
<script>window.global = window;</script>

Or better, add this, on your polyfills.ts
(window as any).global = window;

**Comment by FriOne** [comment] 2018-10-19 08:20
This is duplicate of https://github.com/FriOne/ng-io/issues/2

**Comment by FriOne** [comment] 2018-10-19 08:21
I will try to make it at this weekends

**Closed as completed** 2018-10-28 11:46 UTC
